version: '3.6'
services:
  cocoa-maze-runner:
    image: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:latest-cli
    command: ["--tags", "not @skip"]
    environment:
      APP_LOCATION: /app/build/iOSTestApp.ipa
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_LOCAL_IDENTIFIER: ${BUILDKITE_JOB_ID:-maze-runner}
      DEBUG:
      DEVICE_TYPE: ${DEVICE_TYPE:-IOS_13}
      VERBOSE:
    volumes:
      - ./features/fixtures/ios-swift-cocoapods/output:/app/build
      - ./features/:/app/features/
